import { FolderKanban, Pencil, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Button } from '../components/Button/Button'
import { Card } from '../components/Card/Card'
import { ProjectStatusBadge } from '../components/Project/ProjectStatusBadge'
import { deleteProject, getProjects, type Project } from '../services/api'

export function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [deletingId, setDeletingId] = useState('')
  const loadProjects = useCallback(async () => { setLoading(true); setError(''); try { setProjects(await getProjects()) } catch (reason) { setError(reason instanceof Error ? reason.message : '项目加载失败') } finally { setLoading(false) } }, [])
  useEffect(() => { void loadProjects() }, [loadProjects])
  async function handleDelete(project: Project) { setDeletingId(project.id); setError(''); try { await deleteProject(project.id); setProjects((current) => current.filter((item) => item.id !== project.id)) } catch (reason) { setError(reason instanceof Error ? reason.message : '项目删除失败') } finally { setDeletingId('') } }
  return <div className="space-y-7"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Projects</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">项目列表</h1><p className="mt-2 text-sm text-slate-500">来自 GeekFlow API 的真实项目数据。</p></div><Button asChild><Link to="/projects/new"><Plus size={16} />新建项目</Link></Button></section>{error && <Card className="flex flex-col gap-3 border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 sm:flex-row sm:items-center sm:justify-between"><span>{error}</span><Button variant="outline" size="sm" onClick={() => void loadProjects()}><RefreshCw size={14} />重试</Button></Card>}{loading ? <Card className="grid min-h-72 place-items-center text-sm text-slate-500">正在加载项目…</Card> : projects.length === 0 ? <Card className="grid min-h-72 place-items-center p-8 text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-indigo-50 text-primary"><FolderKanban size={22} /></span><h2 className="mt-4 font-semibold text-slate-900">还没有项目</h2><p className="mt-2 text-sm text-slate-500">创建第一个项目，开始跟踪团队进展。</p><Button asChild className="mt-5"><Link to="/projects/new"><Plus size={16} />创建项目</Link></Button></div></Card> : <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <Card key={project.id} className="p-5 transition-shadow hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-primary"><FolderKanban size={20} /></span><ProjectStatusBadge status={project.status} /></div><h2 className="mt-6 font-semibold text-slate-900">{project.name}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{project.description || '暂无项目描述'}</p><div className="mt-6"><div className="flex justify-between text-xs"><span className="text-slate-500">项目进度</span><span className="font-semibold text-slate-700">{project.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-primary" style={{ width: `${project.progress}%` }} /></div></div><div className="mt-6 flex flex-wrap gap-2"><Button variant="outline" size="sm" asChild><Link to={`/projects/${project.id}`}>查看</Link></Button><Button variant="outline" size="sm" asChild><Link to={`/projects/${project.id}/edit`}><Pencil size={14} />编辑</Link></Button><Button variant="outline" size="sm" disabled={deletingId === project.id} className="text-rose-600 hover:text-rose-700" onClick={() => void handleDelete(project)}><Trash2 size={14} />{deletingId === project.id ? '删除中' : '删除'}</Button></div></Card>)}</section>}</div>
}
