import { CheckSquare, Pencil, Plus, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { deleteTask, getProjectTasks, type Task, type TaskStatus, updateTask } from '../../services/api'
import { Button } from '../Button/Button'
import { Card } from '../Card/Card'
import { TaskPriorityLabel, TaskStatusBadge } from './TaskStatusBadge'

const statusOptions: Array<{ value: TaskStatus; label: string }> = [{ value: 'TODO', label: '待办' }, { value: 'DOING', label: '进行中' }, { value: 'DONE', label: '已完成' }]

export function TaskList({ projectId, refreshKey = 0, onTasksChange }: { projectId: string; refreshKey?: number; onTasksChange?: () => void }) {
  const [tasks, setTasks] = useState<Task[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [changingId, setChangingId] = useState('')
  const loadTasks = useCallback(async () => { setLoading(true); setError(''); try { setTasks(await getProjectTasks(projectId)) } catch (reason) { setError(reason instanceof Error ? reason.message : '任务加载失败') } finally { setLoading(false) } }, [projectId])
  useEffect(() => { void loadTasks() }, [loadTasks, refreshKey])
  async function changeStatus(task: Task, status: TaskStatus) { setChangingId(task.id); setError(''); try { const updated = await updateTask(task.id, { status }); setTasks((current) => current.map((item) => item.id === task.id ? updated : item)); onTasksChange?.() } catch (reason) { setError(reason instanceof Error ? reason.message : '任务状态更新失败') } finally { setChangingId('') } }
  async function remove(task: Task) { setChangingId(task.id); setError(''); try { await deleteTask(task.id); setTasks((current) => current.filter((item) => item.id !== task.id)); onTasksChange?.() } catch (reason) { setError(reason instanceof Error ? reason.message : '任务删除失败') } finally { setChangingId('') } }
  return <section className="space-y-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-semibold text-slate-900">项目任务</h2><p className="mt-1 text-xs text-slate-500">完成任务会自动更新项目进度</p></div><Button size="sm" asChild><Link to={`/projects/${projectId}/tasks/new`}><Plus size={15} />新建任务</Link></Button></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{loading ? <Card className="grid min-h-40 place-items-center text-sm text-slate-500">正在加载任务…</Card> : tasks.length === 0 ? <Card className="grid min-h-40 place-items-center p-6 text-center"><div><span className="mx-auto grid h-9 w-9 place-items-center rounded-lg bg-indigo-50 text-primary"><CheckSquare size={18} /></span><p className="mt-3 text-sm font-medium text-slate-700">还没有任务</p><p className="mt-1 text-xs text-slate-500">添加任务后将自动计算项目进度。</p></div></Card> : <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-165 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">任务名称</th><th className="px-5 py-3 font-medium">状态</th><th className="px-5 py-3 font-medium">优先级</th><th className="px-5 py-3 font-medium">负责人</th><th className="px-5 py-3 font-medium">操作</th></tr></thead><tbody className="divide-y">{tasks.map((task) => <tr key={task.id}><td className="px-5 py-4"><p className="font-medium text-slate-800">{task.title}</p>{task.description && <p className="mt-1 max-w-70 truncate text-xs text-slate-500">{task.description}</p>}</td><td className="px-5 py-4"><div className="space-y-2"><TaskStatusBadge status={task.status} /><select aria-label={`${task.title} 状态`} value={task.status} disabled={changingId === task.id} onChange={(event) => void changeStatus(task, event.target.value as TaskStatus)} className="block rounded-lg border bg-white px-2 py-1 text-xs text-slate-600">{statusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div></td><td className="px-5 py-4"><TaskPriorityLabel priority={task.priority} /></td><td className="px-5 py-4 text-slate-600">{task.assignee || '未分配'}</td><td className="px-5 py-4"><div className="flex gap-2"><Button variant="outline" size="sm" asChild><Link to={`/tasks/${task.id}/edit`}><Pencil size={14} />编辑</Link></Button><Button variant="outline" size="sm" disabled={changingId === task.id} className="text-rose-600 hover:text-rose-700" onClick={() => void remove(task)}><Trash2 size={14} />删除</Button></div></td></tr>)}</tbody></table></div></Card>}</section>
}
